[package]
name = "capsule-ffi"
version = "18.11.2"
authors = ["Capsule Developers <occam_engineering@comcast.com>"]
license = "Apache-2.0"
keywords = ["dpdk", "nfv"]
edition = "2018"
build = "build.rs"
links = "dpdk"

[lib]
name = "capsule_ffi"
doctest = false

[build-dependencies]
bindgen = "0.51"
cc = "1.0"

[dependencies]
