[package]
name = "capsule"
version = "0.1.0"
authors = ["Capsule Developers <occam_engineering@comcast.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.51"

[dependencies]
failure = "0.1"
