[package]
name = "capsule-bench"
version = "0.1.0"
authors = ["Capsule Developers <occam_engineering@comcast.com>"]
license = "Apache-2.0"
keywords = ["dpdk", "nfv"]
publish = false
edition = "2018"
build = "build.rs"

[dev-dependencies]
capsule = { path = "../core", features = ["testils"] }
criterion = "0.3"

[[bench]]
name = "packets"
harness = false
