[package]
name = "skeleton"
version = "0.1.0"
authors = ["Capsule Developers <occam_engineering@comcast.com>"]
edition = "2018"

[[bin]]
name = "skeleton"
path = "main.rs"

[dependencies]
capsule = { path = "../../core" }
failure = "0.1"
log = "0.4"
simplelog = "0.7"
