[package]
name = "capsule"
version = "0.1.0"
authors = ["Capsule Developers <occam_engineering@comcast.com>"]
edition = "2018"

[lib]
name = "capsule"
path = "lib.rs"

[dependencies]
capsule-ffi = { path = "../ffi" }
failure = "0.1"
log = "0.4"
