[package]
name = "capsule-macros"
version = "0.1.0"
authors = ["Capsule Developers <occam_engineering@comcast.com>"]
license = "Apache-2.0"
keywords = []
edition = "2018"
description = "Capsule procedural macros"
categories = []

[lib]
name = "capsule_macros"
proc-macro = true
doctest = false

[dependencies]
darling ="0.10"
quote = "1"
syn = { version = "1.0", features = ["full"] }
